;;; chinese-conv-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from chinese-conv.el

(autoload 'chinese-conv "chinese-conv" "\
Convert a Chinese string, eg. between simplified and traditional forms.
Can be used interactively or non-interactively.

STR is the string to convert.
CONV is one of the conversion type identifiers.
BACKEND is the backend to be used, see `chinese-conv-backend-alist'.

Also see `chinese-conv-replace'.

(fn STR CONV &optional BACKEND)" t)
(autoload 'chinese-conv-replace "chinese-conv" "\
Convert a Chinese string in place.
Can be used interactively or non-interactively.

START is starting position in buffer.
END is the ending position in buffer.
CONV is one of the conversion type identifiers.
BACKEND is the backend to be used, see `chinese-conv-backend-alist'.

Also see `chinese-conv'.

(fn START END CONV &optional BACKEND)" t)
(register-definition-prefixes "chinese-conv" '("chinese-conv-"))

;;; End of scraped data

(provide 'chinese-conv-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; chinese-conv-autoloads.el ends here
