;;; helm-spotify-plus-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from helm-spotify-plus.el

(autoload 'helm-spotify-plus "helm-spotify-plus" "\
Brind up a custom PROMPT asking for the name of the Artist to perform the search and them all the candidates ready to be narrowed." t)
(register-definition-prefixes "helm-spotify-plus" '("helm-spotify-"))

;;; End of scraped data

(provide 'helm-spotify-plus-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; helm-spotify-plus-autoloads.el ends here
