;;; find-by-pinyin-dired-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from find-by-pinyin-dired.el

(autoload 'find-by-pinyin-dired "find-by-pinyin-dired" "\
Search DIR recursively for files/directories matching the PATTERN.
Then run Dired on those files.
PATTERN is sequence of first character of PinYin of each Chinese character.
Space in PATTERN match a number of any Chinese characters.
For example, pattern 'hh tt' find file '好好学习天天向上.txt'.

(fn DIR PATTERN)" t)
(autoload 'find-by-pinyin-in-project-dired "find-by-pinyin-dired" "\
Simlar to `find-by-pinyin-dired' while search directory automatically detected.
The directory is detected by `ffip-project-root' if `find-file-in-project' installed.

(fn PATTERN)" t)
(register-definition-prefixes "find-by-pinyin-dired" '("find-by-pinyin-"))

;;; End of scraped data

(provide 'find-by-pinyin-dired-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; find-by-pinyin-dired-autoloads.el ends here
